version: '3.9'
services:
  api:
    build: .
    ports:
      - "5000:80"
    depends_on:
      - postgres
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: streamhive
      POSTGRES_PASSWORD: streamhive
      POSTGRES_DB: streamhive
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:
